// packages/vue/src/WeekTimeGrid.vue
<template>
  <div
    class="week-time-grid"
    @mouseleave="handleMouseLeave"
    @mouseup="handleMouseUp"
  >
    <!-- 表头 - 时间标签 -->
    <div class="week-time-grid__header">
      <div
        class="week-time-grid__header-cell week-time-grid__header-cell--empty"
      >
        星期/时间
      </div>
      <div
        v-for="(_, cellIndex) in Array(endHour - startHour).fill(null)"
        :key="'time-' + cellIndex"
        class="week-time-grid__header-cell week-time-grid__header-cell--time"
      >
        {{ cellIndex }}
      </div>
    </div>

    <!-- 网格主体 -->
    <div class="week-time-grid__body">
      <!-- 每一行（星期） -->
      <div
        v-for="(dayLabel, dayIndex) in dayLabels"
        :key="'day-' + dayIndex"
        class="week-time-grid__row"
      >
        <!-- 行标签（星期） -->
        <div class="week-time-grid__row-label">{{ dayLabel }}</div>

        <!-- 单元格 -->
        <div
          v-for="(_, cellIndex) in hourLabels"
          :key="'cell-' + dayIndex + '-' + cellIndex"
          class="week-time-grid__cell"
          :class="{
            'week-time-grid__cell--selected': getCellState(dayIndex, cellIndex),
          }"
          @mousedown.stop="handleMouseDown(dayIndex, cellIndex)"
          @mousemove.stop="handleMouseMove(dayIndex, cellIndex)"
          @click.stop="handleCellClick(dayIndex, cellIndex)"
        ></div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  ref,
  computed,
  watch,
  onMounted,
  PropType,
} from "vue";
import {
  WeekTimeGridCore,
  TimeRange,
  WeekTimeGridOptions,
} from "@weektime-picker/core";

export default defineComponent({
  name: "WeekTimeGrid",

  props: {
    // v-model 绑定值
    modelValue: {
      type: Array as PropType<TimeRange[]>,
      default: () => [],
    },
    // 星期标签
    dayLabels: {
      type: Array as PropType<string[]>,
      default: () => [
        "星期一",
        "星期二",
        "星期三",
        "星期四",
        "星期五",
        "星期六",
        "星期日",
      ],
    },
    // 开始小时
    startHour: {
      type: Number,
      default: 0,
    },
    // 结束小时
    endHour: {
      type: Number,
      default: 23,
    },
    // 时间间隔（分钟）
    timeInterval: {
      type: Number,
      default: 60,
    },
    // 颜色主题
    themeColor: {
      type: String,
      default: "#4a89dc",
    },
  },

  emits: ["update:modelValue", "change"],

  setup(props, { emit }) {
    // 创建核心实例
    const core = ref<WeekTimeGridCore | null>(null);
    const rerenderKey = ref(0);

    // 拖动状态跟踪
    const isDragging = ref(false);

    // 计算网格配置
    const gridConfig = computed(() => {
      if (!core.value)
        return { rows: 7, cols: 24, dayLabels: [], hourLabels: [] };
      return core.value.getGridConfig();
    });

    // 提取小时标签
    const hourLabels = computed(() => gridConfig.value.hourLabels);
    const dayLabels = computed(() => gridConfig.value.dayLabels);

    // 初始化核心实例
    const initCore = () => {
      const options: WeekTimeGridOptions = {
        dayLabels: props.dayLabels,
        startHour: props.startHour,
        endHour: props.endHour,
        timeInterval: props.timeInterval,
      };

      core.value = new WeekTimeGridCore(options, handleChange);

      // 设置初始选中范围
      if (props.modelValue.length > 0) {
        core.value.setSelectedRanges(props.modelValue);
      }
    };

    // 处理变更事件
    const handleChange = (ranges: TimeRange[]) => {
      emit("update:modelValue", ranges);
      emit("change", ranges);
    };

    // 获取单元格状态
    const getCellState = (dayIndex: number, cellIndex: number) => {
      if (!core.value) return false;

      const { startHour, timeInterval } = props;
      const intervalsPerHour = 60 / timeInterval;

      // 计算小时和分钟
      const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
      const minute = (cellIndex % intervalsPerHour) * timeInterval;

      return core.value.getCellState(dayIndex, hour, minute);
    };

    // 拖拽状态跟踪
    const dragStartTime = ref<number>(0);
    const hasMoved = ref<boolean>(false);

    // 处理鼠标按下事件
    const handleMouseDown = (dayIndex: number, cellIndex: number) => {
      if (!core.value) return;

      // 记录拖动开始时间和重置移动标志
      dragStartTime.value = Date.now();
      hasMoved.value = false;
      // 注意：这里不立即设置 isDragging，等到真正移动时再设置

      const { startHour, timeInterval } = props;
      const intervalsPerHour = 60 / timeInterval;

      // 计算小时和分钟
      const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
      const minute = (cellIndex % intervalsPerHour) * timeInterval;

      // 开始拖拽准备，但不立即进入拖拽状态
      core.value.handleDragStart(dayIndex, hour, minute);
    };

    // 处理鼠标移动事件
    const handleMouseMove = (dayIndex: number, cellIndex: number) => {
      if (!core.value) return;

      // 检查是否已经按下鼠标（通过时间戳判断）
      if (dragStartTime.value === 0) return;

      // 第一次移动时，设置为拖拽状态
      if (!isDragging.value) {
        isDragging.value = true;
      }

      // 标记已经移动，这是真正的拖动
      hasMoved.value = true;

      const { startHour, timeInterval } = props;
      const intervalsPerHour = 60 / timeInterval;

      // 计算小时和分钟
      const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
      const minute = (cellIndex % intervalsPerHour) * timeInterval;

      core.value.handleDragMove(dayIndex, hour, minute);

      // 触发重新渲染以显示拖动预览
      rerenderKey.value += 1;
    };

    // 处理鼠标抬起事件（只处理拖拽结束）
    const handleMouseUp = () => {
      // 只在拖拽状态下处理
      if (!core.value || !isDragging.value) {
        // 重置拖拽准备状态
        dragStartTime.value = 0;
        hasMoved.value = false;
        return;
      }

      // 结束拖动操作
      core.value.handleDragEnd();

      // 重置所有状态
      isDragging.value = false;
      hasMoved.value = false;
      dragStartTime.value = 0;

      // 触发重新渲染
      rerenderKey.value += 1;
    };

    // 处理单元格点击事件（直接点击，不拖动）
    const handleCellClick = (dayIndex: number, cellIndex: number) => {
      // 如果正在拖拽或刚刚完成拖拽，阻止点击
      if (!core.value || isDragging.value || hasMoved.value) {
        // 重置状态
        dragStartTime.value = 0;
        hasMoved.value = false;
        return;
      }

      const { startHour, timeInterval } = props;
      const intervalsPerHour = 60 / timeInterval;

      // 计算小时和分钟
      const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
      const minute = (cellIndex % intervalsPerHour) * timeInterval;

      // 直接调用核心方法处理点击
      core.value.handleCellClick(dayIndex, hour, minute);

      // 重置状态
      dragStartTime.value = 0;
      hasMoved.value = false;

      // 触发重新渲染
      rerenderKey.value += 1;
    };

    // 处理鼠标离开事件
    const handleMouseLeave = () => {
      if (!core.value || !isDragging.value) return;

      core.value.handleDragEnd();

      // 重置拖动状态
      isDragging.value = false;
      hasMoved.value = false;
      dragStartTime.value = 0;

      // 触发重新渲染
      rerenderKey.value += 1;
    };

    // 监听属性变化
    watch(
      () => [
        props.dayLabels,
        props.startHour,
        props.endHour,
        props.timeInterval,
      ],
      () => {
        // 重新初始化核心实例
        initCore();
      },
      { deep: true }
    );

    // 监听 modelValue 变化
    watch(
      () => props.modelValue,
      (newValue) => {
        if (core.value) {
          // 检查新旧值是否相同，避免不必要的更新
          const currentRanges = core.value.getSelectedRanges();
          rerenderKey.value += 1;

          if (JSON.stringify(newValue) !== JSON.stringify(currentRanges)) {
            // 更新选中范围
            core.value.setSelectedRanges(newValue);
          }
        }
      },
      { deep: true }
    );

    // 组件挂载时初始化
    onMounted(() => {
      initCore();
    });

    return {
      gridConfig,
      hourLabels,
      dayLabels,
      getCellState,
      handleMouseDown,
      handleMouseMove,
      handleMouseUp,
      handleMouseLeave,
      handleCellClick,
      rerenderKey,
    };
  },
});
</script>

<style>
/* WeekTimeGrid 组件样式 */
.week-time-grid {
  display: flex;
  flex-direction: column;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  overflow: hidden;
  user-select: none;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
    Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
  --label-width: 80px;
}

/* Header 样式 */
.week-time-grid__header {
  display: flex;
  background-color: #f5f5f5;
  border-bottom: 1px solid #e0e0e0;
  box-sizing: border-box;
  position: relative;
}

.week-time-grid__header-cell {
  text-align: center;
  font-size: 12px;
  color: #666;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  box-sizing: border-box;
  padding: 8px 4px;
  position: relative;
  flex: 1;
  min-width: 0;
}

.week-time-grid__header-cell--empty {
  flex: 0 0 var(--label-width);
  width: var(--label-width);
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f5f5f5;
}

/* Header中的divider线 */
.week-time-grid__header-cell:not(:last-child)::after {
  content: "";
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 1px;
  background-color: #e0e0e0;
}

/* Body 样式 */
.week-time-grid__body {
  display: flex;
  flex-direction: column;
}

.week-time-grid__row {
  display: flex;
  box-sizing: border-box;
  position: relative;
}

.week-time-grid__row:not(:last-child) {
  border-bottom: 1px solid #e0e0e0;
}

.week-time-grid__row-label {
  flex: 0 0 var(--label-width);
  width: var(--label-width);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  background-color: #f9f9f9;
  box-sizing: border-box;
  padding: 8px;
  position: relative;
}

.week-time-grid__row-label::after {
  content: "";
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 1px;
  background-color: #e0e0e0;
}

/* Cell中的divider线 */
.week-time-grid__cell {
  flex: 1;
  height: 36px;
  cursor: pointer;
  transition: background-color 0.1s ease;
  box-sizing: border-box;
  min-width: 0;
  position: relative;
}

.week-time-grid__cell:not(:last-child)::after {
  content: "";
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 1px;
  background-color: #e0e0e0;
}

.week-time-grid__cell:hover {
  background-color: #f0f7ff;
}

.week-time-grid__cell--selected {
  background-color: v-bind(themeColor);
}

.week-time-grid__cell--selected:hover {
  background-color: v-bind(themeColor);
}

/* 响应式优化 */
@media (max-width: 768px) {
  .week-time-grid__header-cell,
  .week-time-grid__cell {
    min-width: 20px;
  }

  .week-time-grid__header-cell {
    font-size: 10px;
    padding: 2px 1px;
  }

  .week-time-grid__cell {
    height: 24px;
  }
}
</style>

// packages/react/src/WeekTimeGrid.tsx
import React, { useEffect, useRef, useState } from "react";
import {
  WeekTimeGridCore,
  TimeRange,
  WeekTimeGridOptions,
} from "weektime-picker-core";
import "./WeekTimeGrid.css";

export interface WeekTimeGridProps {
  /** 选中的时间范围数组 */
  value?: TimeRange[];
  /** 选中变化时的回调函数 */
  onChange?: (ranges: TimeRange[]) => void;
  /** 星期标签 */
  dayLabels?: string[];
  /** 开始小时 */
  startHour?: number;
  /** 结束小时 */
  endHour?: number;
  /** 时间间隔（分钟） */
  timeInterval?: number;
  /** 主题颜色 */
  themeColor?: string;
  /** 单元格宽度（像素），默认为0表示自适应 */
  cellWidth?: number;
}

/**
 * 周时间网格组件
 */
export const WeekTimeGrid: React.FC<WeekTimeGridProps> = ({
  value = [],
  onChange,
  dayLabels = [
    "星期一",
    "星期二",
    "星期三",
    "星期四",
    "星期五",
    "星期六",
    "星期日",
  ],
  startHour = 0,
  endHour = 24,
  timeInterval = 60,
  themeColor = "#4a89dc",
  cellWidth = 0,
}) => {
  // 核心实例引用
  const coreRef = useRef<WeekTimeGridCore | null>(null);

  // 网格配置状态
  const [gridConfig, setGridConfig] = useState<{
    rows: number;
    cols: number;
    dayLabels: string[];
    hourLabels: string[];
  }>(() => {
    // 初始化时计算网格配置
    const options: WeekTimeGridOptions = {
      dayLabels,
      startHour,
      endHour,
      timeInterval,
    };
    const core = new WeekTimeGridCore(options);
    const config = core.getGridConfig();

    coreRef.current = core;

    return config;
  });

  // 拖动状态跟踪 - 使用state而不是ref来确保同步
  const [isDragging, setIsDragging] = useState(false);
  const dragStartTimeRef = useRef<number>(0);
  const hasMovedRef = useRef(false);

  // 强制重新渲染的状态
  const [renderKey, setRenderKey] = useState(0);

  // 获取单元格状态
  const getCellState = (dayIndex: number, cellIndex: number): boolean => {
    if (!coreRef.current) return false;

    const intervalsPerHour = 60 / timeInterval;

    // 计算小时和分钟
    const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
    const minute = (cellIndex % intervalsPerHour) * timeInterval;

    return coreRef.current.getCellState(dayIndex, hour, minute);
  };

  // 处理鼠标按下事件
  const handleMouseDown = (
    dayIndex: number,
    cellIndex: number,
    e: React.MouseEvent
  ) => {
    e.preventDefault();
    e.stopPropagation();

    if (!coreRef.current) return;

    // 记录拖动开始时间和重置移动标志
    dragStartTimeRef.current = Date.now();
    hasMovedRef.current = false;
    // 注意：这里不立即设置 isDragging，等到真正移动时再设置

    const intervalsPerHour = 60 / timeInterval;
    const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
    const minute = (cellIndex % intervalsPerHour) * timeInterval;

    // 开始拖拽准备，但不立即进入拖拽状态
    coreRef.current.handleDragStart(dayIndex, hour, minute);
  };

  // 处理鼠标移动事件
  const handleMouseMove = (
    dayIndex: number,
    cellIndex: number,
    e: React.MouseEvent
  ) => {
    e.stopPropagation();
    if (!coreRef.current) return;

    // 检查是否已经按下鼠标（通过时间戳判断）
    if (dragStartTimeRef.current === 0) return;

    // 第一次移动时，设置为拖拽状态
    if (!isDragging) {
      setIsDragging(true);
    }

    // 标记已经移动，这是真正的拖动
    hasMovedRef.current = true;

    const intervalsPerHour = 60 / timeInterval;
    const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
    const minute = (cellIndex % intervalsPerHour) * timeInterval;

    coreRef.current.handleDragMove(dayIndex, hour, minute);

    // 触发重新渲染以显示拖动预览
    setRenderKey((prev) => prev + 1);
  };

  // 处理鼠标抬起事件（只处理拖拽结束）
  const handleMouseUp = (e: React.MouseEvent) => {
    e.stopPropagation();

    // 只在拖拽状态下处理
    if (!coreRef.current || !isDragging) {
      // 重置拖拽准备状态
      dragStartTimeRef.current = 0;
      hasMovedRef.current = false;
      return;
    }

    // 结束拖动操作
    coreRef.current.handleDragEnd();

    // 重置所有状态
    setIsDragging(false);
    hasMovedRef.current = false;
    dragStartTimeRef.current = 0;

    // 触发重新渲染
    setRenderKey((prev) => prev + 1);

    // 手动触发onChange回调
    if (onChange) {
      const ranges = coreRef.current.getSelectedRanges();
      console.log(`[MouseUp] 拖动结果:`, ranges);
      onChange(ranges);
    }
  };

  // 处理单元格点击事件（直接点击，不拖动）
  const handleCellClick = (
    dayIndex: number,
    cellIndex: number,
    e: React.MouseEvent
  ) => {
    e.stopPropagation();

    console.log(
      `[Click] 触发点击事件, isDragging=${isDragging}, hasMoved=${hasMovedRef.current}`
    );

    // 如果正在拖拽或刚刚完成拖拽，阻止点击
    if (!coreRef.current || isDragging || hasMovedRef.current) {
      console.log(
        `[Click] 被阻止: isDragging=${isDragging}, hasMoved=${hasMovedRef.current}`
      );
      // 重置状态
      dragStartTimeRef.current = 0;
      hasMovedRef.current = false;
      return;
    }

    const intervalsPerHour = 60 / timeInterval;
    const hour = Math.floor(cellIndex / intervalsPerHour) + startHour;
    const minute = (cellIndex % intervalsPerHour) * timeInterval;

    console.log(
      `[Click] 执行点击操作: day=${dayIndex}, cell=${cellIndex}, hour=${hour}, minute=${minute}, endHour=${endHour}, cols=${gridConfig.cols}`
    );

    coreRef.current.handleCellClick(dayIndex, hour, minute);

    // 重置状态
    dragStartTimeRef.current = 0;
    hasMovedRef.current = false;

    // 强制重新渲染
    setRenderKey((prev) => prev + 1);

    // 手动触发onChange回调
    if (onChange) {
      const ranges = coreRef.current.getSelectedRanges();
      console.log(`[Click] 结果范围:`, ranges);
      onChange(ranges);
    }
  };

  // 处理鼠标离开事件
  const handleMouseLeave = () => {
    if (!coreRef.current || !isDragging) return;

    console.log(`[MouseLeave] 结束拖动`);

    coreRef.current.handleDragEnd();

    // 重置拖动状态
    setIsDragging(false);
    hasMovedRef.current = false;

    // 触发重新渲染
    setRenderKey((prev) => prev + 1);

    // 手动触发onChange回调
    if (onChange) {
      const ranges = coreRef.current.getSelectedRanges();
      onChange(ranges);
    }
  };

  // 监听 props 变化
  useEffect(() => {
    // 重新初始化核心实例
    const options: WeekTimeGridOptions = {
      dayLabels,
      startHour,
      endHour,
      timeInterval,
    };

    // 创建新的核心实例，不传入onChange回调避免循环
    const core = new WeekTimeGridCore(options);
    coreRef.current = core;

    // 设置初始选中范围
    if (value && value.length > 0) {
      core.setSelectedRanges(value);
    }

    // 更新网格配置
    const config = core.getGridConfig();
    console.log(
      `[GridConfig] cols=${config.cols}, endHour=${endHour}, startHour=${startHour}`
    );
    setGridConfig(config);

    // 触发重新渲染
    // setRenderKey((prev) => prev + 1);
  }, [dayLabels, startHour, endHour, timeInterval]);

  // 监听 value 变化
  useEffect(() => {
    if (coreRef.current && value) {
      // 检查新旧值是否相同，避免不必要的更新
      const currentRanges = coreRef.current.getSelectedRanges();
      if (JSON.stringify(currentRanges) !== JSON.stringify(value)) {
        // 更新选中范围
        coreRef.current.setSelectedRanges(value);
        // 触发重新渲染
        // setRenderKey((prev) => prev + 1);
      }
    }
  }, [value]);

  return (
    <div
      className="week-time-grid"
      onMouseLeave={handleMouseLeave}
      onMouseUp={handleMouseUp}
      style={{ "--theme-color": themeColor } as React.CSSProperties}
    >
      {/* 表头 - 时间标签 */}
      <div className="week-time-grid__header">
        <div className="week-time-grid__header-cell week-time-grid__header-cell--empty">
          星期/时间
        </div>
        {Array.from({ length: endHour - startHour }).map((_, cellIndex) => {
          return (
            <div
              key={`time-${cellIndex}`}
              className="week-time-grid__header-cell week-time-grid__header-cell--time"
            >
              {cellIndex}
            </div>
          );
        })}
      </div>
      {/* 网格主体 */}
      <div className="week-time-grid__body">
        {gridConfig.dayLabels.map((dayLabel, dayIndex) => (
          <div key={`day-${dayIndex}`} className="week-time-grid__row">
            {/* 行标签（星期） */}
            <div className="week-time-grid__row-label">{dayLabel}</div>

            {/* 单元格 */}
            {Array.from({ length: gridConfig.cols }).map((_, cellIndex) => (
              <div
                key={`cell-${dayIndex}-${cellIndex}-${renderKey}`}
                className={`week-time-grid__cell ${
                  getCellState(dayIndex, cellIndex)
                    ? "week-time-grid__cell--selected"
                    : ""
                }`}
                style={
                  cellWidth > 0
                    ? { flex: "0 0 auto", width: `${cellWidth}px` }
                    : {}
                }
                data-day={dayIndex}
                data-cell={cellIndex}
                onMouseDown={(e) => handleMouseDown(dayIndex, cellIndex, e)}
                onMouseMove={(e) => handleMouseMove(dayIndex, cellIndex, e)}
                onClick={(e) => handleCellClick(dayIndex, cellIndex, e)}
              ></div>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
};

export default WeekTimeGrid;
